### ISSUE TITLE
Using GC hooks to free memory

### ISSUE THREAD

**Issue by Fiveside** [lestrrat-go/libxml2#36]
The current pattern that `go-libxml2` advertises involves manually freeing memory after we're done using it.  Can we use object finalizers to free up allocated memory instead?  I've taken a quick look at converting the library to do so, but it looks there was a conscious effort to allow external access to the low level clib stuff.  

Does automatic garbage collection still make sense given the public access to the low level clib interface?

**Comment by lestrrat** [comment]
I think finalizers being set using SetFinalizer are not guaranteed to fire in any fixed order, or in any given timeframe, which may be problematic if we have a dependency on the order of execution?
I believe in Go you must use proper defer calls to create reliable hooks to destroy resources.

**Comment by Fiveside** [comment]
Actually, finalizers are run in dependency order.  If a structure contains a reference to another object, and both have finalizers associated with them, then the first structure's finalizer is run before the second.  There's a good write up on finalizers' order of execution here https://golang.org/pkg/runtime/#SetFinalizer

**Comment by lestrrat** [comment]
Yeah yeah, I remember reading up on this stuff when I was writing this.
And I think I now remember why Finalizers are not appropriate here:
libxml2 resources need to be freed, but only when necessary -- the most prominent case is where they do not need to be freed is when the node is attached to another node. In that case the "root" node is the only one that can be freed: freeing the root node frees the entire structure, and you are NOT to call free on the rest.
This is just a one occasion, but here's the thing: in libxml2 there are subtle cases where explicit free is required, and there are cases where you are explicitly not allowed to free. My experience tells me that in such cases  making calls explicit is the safer choice than trying to outsmart libxml2.

Having said that, if you are to come up with a comprehensive pattern that manages and a PR for it, I'm all game. I'm just not going to spend time on it.

On the other hand, I have an [half-baked libxml2 clone in Go](https://github.com/lestrrat/helium), which does NOT need memory management. It's abandoned because (IIRC) I think I messed something up in the guts of it but I couldn't figure out how to make it pass entity declaration tests.
