### ISSUE TITLE
XSD validation XML path

### ISSUE THREAD

**Issue by airedwin** [lestrrat-go/libxml2#74]
I saw a previous issue regarding getting the line number of the error when doing XSD validation. Since that doesn't seem to be possible, is there a way we can get the XML path of element with the error? That will help with troubleshooting XML errors.

**Comment by lestrrat** [comment]
Does the original libxml2 (xmllint or the like) provide this information?
If yes, can you please provide a test case where we can see it in action?

If libxml2 doesn't give it to you, then most likely (take this with a grain of salt, as I haven't really delved into the gory details of libxml2 recently) the answer is no, we can't. I'm willing to be convinced otherwise, though.
